language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install --use-mirrors git+https://github.com/landscapeio/pylint-plugin-utils.git@develop"
  - "pip install --use-mirrors --editable ."
script: python test/test_func.py
